

export const USER_REQUEST_PENDING="USER_REQUEST_PENDING"

export const USER_LOGIN_REQUEST_SUCCESS ="USER_LOGIN_REQUEST_SUCCESS"

export const USER_REGISTER_REQUEST_SUCCESS="USER_REGISTER_REQUEST_SUCCESS"

export const USER_REQUEST_FAILURE="USER_REQUEST_FAILURE"