

export const USER_REQUEST_PENDING="USER_REQUEST_PENDING"

export const USER_LOGIN_REQUEST_SUCCESS ="USER_LOGIN_REQUEST_SUCCESS"

export const USER_DATA_REQUEST_SUCCESS="USER_DATA_REQUEST_SUCCESS"

export const USER_REQUEST_FAILURE="USER_REQUEST_FAILURE"

export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS"

export const SEARCH_SINGLE_STOCKS="SEARCH_SINGLE_STOCKS"
